name: Build and Deploy Storybook
on: push

workflow_dispatch:
  #pull_request:
  #types: [opened]
permissions:
  pages: write
  contents: read
  id-token: write

echo:
# jobs:
#   # Build job
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout 🛎️
#         uses: actions/checkout@v3
#       - name: Install and Build 🔧
#         run: | # Install npm packages and build the Storybook files
#           npm install
#           npm run build-storybook
#       - name: Deploy 🚀
#         uses: JamesIves/github-pages-deploy-action@3.6.2
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           BRANCH: main # The branch the action should deploy to.
#           FOLDER: docs-build # The folder that the build-storybook script generates files.
#           CLEAN: true # Automatically remove deleted files from the deploy branch
#           TARGET_FOLDER: ${{GITHUB_REF_NAME}} # The folder that we serve our Storybook files from
